# Generated by Django 5.0 on 2023-12-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_count', models.IntegerField(default=0)),
            ],
        ),
    ]
